#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

VENV_PATH="${PWD}/.venv"

if [[ ! -d "${VENV_PATH}" ]]; then
    python3 -m venv "${VENV_PATH}"
fi

"${VENV_PATH}/bin/python" -m pip install --upgrade pip
"${VENV_PATH}/bin/python" -m pip install --requirement requirements.txt
